### ISSUE TITLE
Найти данные

### ISSUE THREAD

**Issue by Sereni** [Sereni/Moore-tagger#1]
Надо найти данные. Тестировали его на Penn Treebank Wall Street Journal (WSJ) corpus, а тренировали на чём, на нём же? Если да, то нашли.

**Comment by lizaku** [comment]
А где ты его нашла? В nltk только сэмпл, а сам Penn доступа не предлагает. Или того, что в nltk (40k слов), хватит?

**Comment by Sereni** [comment]
Справедливо. Надо спросить знающих людей, хватит ли, где взять, или чем заменить.

**Comment by ElizavetaKuzmenko** [comment]
Знающими людьми могут быть также Кира Дроганова и О. Ляшевская, подсказывают мне.

**Comment by lizaku** [comment]
Как вариант, наверно, брауновский корпус подойдет. Он тоже хорошо размечен и его миллион.

**Comment by Sereni** [comment]
А брауновский разве есть открытый? У меня где-то лежит два куска по 30 МБ,
не знаю откуда их взяли.

21 января 2016 г., 18:19 пользователь Elizaveta Kuzmenko <
notifications@github.com> написал:

**Comment by lizaku** [comment]
Он как раз вроде весь в nltk.

**Comment by lizaku** [comment]
Короче, надо делать не на языке оригинала, вопрос отпал сам собой. Эля говорит, надо на русском, тогда данные есть.

**Comment by elmiram** [comment]
Данные есть, даже полно. мы же делали таггер в прошлом году. просто другой. 
но давайте тогда делать таггер только по частям речи. без прочих грам.характеристик.

**Comment by elmiram** [comment]
Давайте делать русский таггер. Данные русские у нас есть!
А парсить только части речи будем.

А еще апдейт:
даже если у нас есть готовый корпус, нужно все равно что-то выкачать откуда-нибудь и сделать из этого корпус. Это обязательная часть задания.

**Comment by elmiram** [comment]
Мы начали выкачивать статьи c hse.ru.
