### ISSUE TITLE
Сделать парсер для фич

### ISSUE THREAD

**Issue by Sereni** [Sereni/Moore-tagger#2]
- Whether the word contains a capital letter
- Whether the word contains a digit
- Whether the word contains a hyphen
- Lower-cased prefixes of the word up to four characters
- Lower-cased suffixes of the word up to four characters
- The Shape 1 feature for the word
- The Shape 2 feature for the word
- The full lower-cased word
- The full word
- A distributional-similarity-based class for the full word

Во всех фичах нет различия между цифрами (можно сразу заменить на 0).
_Shape 1_: представляем слово Сен-Тропе123 в виде Xxx-Xxxxx000. Не различаем заглавные буквы, строчные буквы и цифры. Остальные символы оставляем на месте.
_Shape 2_: Сен-Тропе123 -> Xx-Xx0. Все последовательности одинаковых символов в _Shape 1_ заменяем на один такой же символ.
Последнее -- это один из 256 кластеров, в который закинулись какие-то токены по какому-то алгоритму, плюс один кластер для того, что не нашлось в корпусе. Как-то мутно.
Дальше теги для каждого токена склеиваются с предыдущим и следующим, но это я как-нибудь напишу в отдельной issue.

**Comment by elmiram** [comment]
Я добавила в hyphens еще палочек. Возможно, некоторые из них тире =) 
но почему бы не перестраховаться.

а что там такого плохого в регулярных выражениях, где написано performance hit?

**Comment by Sereni** [comment]
То, что они регулярные выражения)
