### ISSUE TITLE
Кластеринг (фича)

### ISSUE THREAD

**Issue by Sereni** [Sereni/Moore-tagger#3]
Сделать кластеризатор, как написано здесь:
http://www.aclweb.org/anthology/P08-1#page=799
А не можем ли мы на это забить, или хотя бы упростить как-нибудь?

**Comment by Sereni** [comment]
Даже точно нужно упростить, в статье написано время тренировки модели, и оно не для наших машинок.
В общем, я бы использовала scikit, только пока не пойму, на каких фичах они их кластеризуют. Триграммы, что ли.

**Comment by elmiram** [comment]
Короче, рассказываю.
Uszkoreit, Brants кластеризуют без фичей. Там просто биграммная языковая модель, в которой каждому слову дается какой-то условный класс и выбирается какая-то функция. А потом специальная программа должна пожонглировать словами и классами так, чтобы слова поделились на классы и функция получила максимальное (или минимальное) значение.

У них такое время тренировки модели (типа несколько дней), потому что они тренируют модель на огроменном корпусе (121+миллиардов токенов).

Я хотеля взять похожую кластеризацию из статьи,  на которую ссылаются Uszkoreit, Brants: [Martin et al. 1998](https://www.researchgate.net/profile/Hermann_Ney/publication/222496856_Algorithms_for_bigram_and_trigram_word_clustering/links/53f35efb0cf2dd48950cb2e1.pdf)

Она работает медленнее, зато лично мне ее понять и написать руками было проще. Я думала, что раз у нас корпус не такой большой, то не так важно, что кластеризация медленнее.
Но она реально чертовски медленная. Это плохо.

Поэтому я решила это не делать, а взяла те же униграммы\биграммы из корпуса, придумала какие-то фичи и сделала кластеринг scikit'ом.  ( Kmeans; работает минут 20).
Вот фичи:
1) words frequency,
2) how many of top 100 frequent words occur after word,
3) how many of top 100 frequent words occur before word,
4) length of word,
5) frequency of top 10 bigrams where the word is in the second place,
6) frequency of top 10 bigrams where the word is in the first place

Кластеринг в каких-то местах похож на то, что получилось у чуваков в нашей статье, а в каких-то вообще какой-то странный.. 

Можно попробовать, подумать про более аккуратные фичи и кластеризовать сайкитом дальше.

**Comment by elmiram** [comment]
Биграммы и униграммы отсюда http://ruscorpora.ru/corpora-freq.html
Кластеры получились вот такие https://drive.google.com/open?id=0B50CecJpbfHxSE5lZUhkSEJVY1k
