### ISSUE TITLE
Классификация

### ISSUE THREAD

**Issue by lizaku** [Sereni/Moore-tagger#4]
Натренировать модель на LinearSVC

**Comment by lizaku** [comment]
У меня вопрос: что такое development set в их статье?

**Comment by lizaku** [comment]
Тут ещё идут всякие навороты типа комбинирования фичей и их иерархии, это потом, а пока мы просто тренируем модель на всех фичах.

**Comment by Sereni** [comment]
А почему linear svc, если там "Our models are trained by optimizing the multiclass SVM hinge loss objective"?

**Comment by Sereni** [comment]
А, это же подкласс.

**Comment by Sereni** [comment]
Используем в итоге SGD Classifier (stochastic gradient descent). А у меня такой вопрос возник вдруг: чего с омонимией делать? Если в корпусе попались два слова одинаковых графически, оба тега записываем? Как он потом с ума не сойдёт? :)
